<a href="https://colab.research.google.com/github/Riyasawalkar/Churn-Data-Analysis/blob/main/HSBC_data_set_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [ ]:
import pandas as pd

In [ ]:
import numpy as np

In [ ]:
df=pd.read_csv('/content/drive/MyDrive/hsbc_bank_loan_data.csv.csv')

In [ ]:
df.head()

,Loan_ID,Gender,Married,Dependents,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area,Loan_Status
0,LP001002,Male,No,0,Graduate,No,5849,0.0,NaN,360.0,1.0,Urban,Y
1,LP001003,Male,Yes,1,Graduate,No,4583,1508.0,128.0,360.0,1.0,Rural,N
2,LP001005,Male,Yes,0,Graduate,Yes,3000,0.0,66.0,360.0,1.0,Urban,Y
3,LP001006,Male,Yes,0,Not Graduate,No,2583,2358.0,120.0,360.0,1.0,Urban,Y
4,LP001008,Male,No,0,Graduate,No,6000,0.0,141.0,360.0,1.0,Urban,Y

In [ ]:
df.isna().sum()

Loan_ID               0
Gender               13
Married               3
Dependents           15
Education             0
Self_Employed        32
ApplicantIncome       0
CoapplicantIncome     0
LoanAmount           22
Loan_Amount_Term     14
Credit_History       50
Property_Area         0
Loan_Status           0
dtype: int64

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 614 entries, 0 to 613
Data columns (total 13 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Loan_ID            614 non-null    object
 1   Gender             601 non-null    object
 2   Married            611 non-null    object
 3   Dependents         599 non-null    object
 4   Education          614 non-null    object
 5   Self_Employed      582 non-null    object
 6   ApplicantIncome    614 non-null    int64
 7   CoapplicantIncome  614 non-null    float64
 8   LoanAmount         592 non-null    float64
 9   Loan_Amount_Term   600 non-null    float64
 10  Credit_History     564 non-null    float64
 11  Property_Area      614 non-null    object
 12  Loan_Status        614 non-null    object
dtypes: float64(4), int64(1), object(8)
memory usage: 62.5+ KB

In [ ]:

# List of numerical columns to fill
numerical_cols = ['LoanAmount', 'Loan_Amount_Term', 'Credit_History', 'Dependents']

In [ ]:
# Ensure columns are numeric
df[numerical_cols] = df[numerical_cols].apply(pd.to_numeric, errors='coerce')

In [ ]:
# Fill numerical columns with the mean
df[numerical_cols] = df[numerical_cols].fillna(df[numerical_cols].mean())

In [ ]:
print(df)

      Loan_ID  Gender Married  Dependents     Education Self_Employed  \
0    LP001002    Male      No    0.000000      Graduate            No
1    LP001003    Male     Yes    1.000000      Graduate            No
2    LP001005    Male     Yes    0.000000      Graduate           Yes
3    LP001006    Male     Yes    0.000000  Not Graduate            No
4    LP001008    Male      No    0.000000      Graduate            No
..        ...     ...     ...         ...           ...           ...
609  LP002978  Female      No    0.000000      Graduate            No
610  LP002979    Male     Yes    0.554745      Graduate            No
611  LP002983    Male     Yes    1.000000      Graduate            No
612  LP002984    Male     Yes    2.000000      Graduate            No
613  LP002990  Female      No    0.000000      Graduate           Yes

     ApplicantIncome  CoapplicantIncome  LoanAmount  Loan_Amount_Term  \
0               5849                0.0  146.412162             360.0
1               4583             1508.0  128.000000             360.0
2               3000                0.0   66.000000             360.0
3               2583             2358.0  120.000000             360.0
4               6000                0.0  141.000000             360.0
..               ...                ...         ...               ...
609             2900                0.0   71.000000             360.0
610             4106                0.0   40.000000             180.0
611             8072              240.0  253.000000             360.0
612             7583                0.0  187.000000             360.0
613             4583                0.0  133.000000             360.0

     Credit_History Property_Area Loan_Status
0               1.0         Urban           Y
1               1.0         Rural           N
2               1.0         Urban           Y
3               1.0         Urban           Y
4               1.0         Urban           Y
..              ...           ...         ...
609             1.0         Rural           Y
610             1.0         Rural           Y
611             1.0         Urban           Y
612             1.0         Urban           Y
613             0.0     Semiurban           N

[614 rows x 13 columns]

In [ ]:
df.isna().sum()

Loan_ID               0
Gender               13
Married               3
Dependents            0
Education             0
Self_Employed        32
ApplicantIncome       0
CoapplicantIncome     0
LoanAmount            0
Loan_Amount_Term      0
Credit_History        0
Property_Area         0
Loan_Status           0
dtype: int64

In [ ]:

# List of boolean columns to fill
boolean_cols = ['Gender', 'Married','Self_Employed']

In [ ]:
# Fill boolean columns with the mode (most frequent value)
for col in boolean_cols:
    df[col] = df[col].fillna(df[col].mode()[0])

In [ ]:
print(df)

      Loan_ID  Gender Married  Dependents     Education Self_Employed  \
0    LP001002    Male      No    0.000000      Graduate            No
1    LP001003    Male     Yes    1.000000      Graduate            No
2    LP001005    Male     Yes    0.000000      Graduate           Yes
3    LP001006    Male     Yes    0.000000  Not Graduate            No
4    LP001008    Male      No    0.000000      Graduate            No
..        ...     ...     ...         ...           ...           ...
609  LP002978  Female      No    0.000000      Graduate            No
610  LP002979    Male     Yes    0.554745      Graduate            No
611  LP002983    Male     Yes    1.000000      Graduate            No
612  LP002984    Male     Yes    2.000000      Graduate            No
613  LP002990  Female      No    0.000000      Graduate           Yes

     ApplicantIncome  CoapplicantIncome  LoanAmount  Loan_Amount_Term  \
0               5849                0.0  146.412162             360.0
1               4583             1508.0  128.000000             360.0
2               3000                0.0   66.000000             360.0
3               2583             2358.0  120.000000             360.0
4               6000                0.0  141.000000             360.0
..               ...                ...         ...               ...
609             2900                0.0   71.000000             360.0
610             4106                0.0   40.000000             180.0
611             8072              240.0  253.000000             360.0
612             7583                0.0  187.000000             360.0
613             4583                0.0  133.000000             360.0

     Credit_History Property_Area Loan_Status
0               1.0         Urban           Y
1               1.0         Rural           N
2               1.0         Urban           Y
3               1.0         Urban           Y
4               1.0         Urban           Y
..              ...           ...         ...
609             1.0         Rural           Y
610             1.0         Rural           Y
611             1.0         Urban           Y
612             1.0         Urban           Y
613             0.0     Semiurban           N

[614 rows x 13 columns]

In [ ]:
df.isna().sum()

Loan_ID              0
Gender               0
Married              0
Dependents           0
Education            0
Self_Employed        0
ApplicantIncome      0
CoapplicantIncome    0
LoanAmount           0
Loan_Amount_Term     0
Credit_History       0
Property_Area        0
Loan_Status          0
dtype: int64

In [ ]:
df.head()

,Loan_ID,Gender,Married,Dependents,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area,Loan_Status
0,LP001002,Male,No,0.0,Graduate,No,5849,0.0,146.412162,360.0,1.0,Urban,Y
1,LP001003,Male,Yes,1.0,Graduate,No,4583,1508.0,128.000000,360.0,1.0,Rural,N
2,LP001005,Male,Yes,0.0,Graduate,Yes,3000,0.0,66.000000,360.0,1.0,Urban,Y
3,LP001006,Male,Yes,0.0,Not Graduate,No,2583,2358.0,120.000000,360.0,1.0,Urban,Y
4,LP001008,Male,No,0.0,Graduate,No,6000,0.0,141.000000,360.0,1.0,Urban,Y

In [ ]:

# Create the 'TotalIncome' column
df['TotalIncome'] = df['ApplicantIncome'] + df['CoapplicantIncome']

In [ ]:
df.head()

,Loan_ID,Gender,Married,Dependents,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area,Loan_Status,TotalIncome
0,LP001002,Male,No,0.0,Graduate,No,5849,0.0,146.412162,360.0,1.0,Urban,Y,5849.0
1,LP001003,Male,Yes,1.0,Graduate,No,4583,1508.0,128.000000,360.0,1.0,Rural,N,6091.0
2,LP001005,Male,Yes,0.0,Graduate,Yes,3000,0.0,66.000000,360.0,1.0,Urban,Y,3000.0
3,LP001006,Male,Yes,0.0,Not Graduate,No,2583,2358.0,120.000000,360.0,1.0,Urban,Y,4941.0
4,LP001008,Male,No,0.0,Graduate,No,6000,0.0,141.000000,360.0,1.0,Urban,Y,6000.0

In [ ]:
# Drop the 'ApplicantIncome' and 'CoapplicantIncome' columns
df.drop(columns=['ApplicantIncome', 'CoapplicantIncome','Loan_ID'], inplace=True)

In [ ]:
df.head()

,Gender,Married,Dependents,Education,Self_Employed,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area,Loan_Status,TotalIncome
0,Male,No,0.0,Graduate,No,146.412162,360.0,1.0,Urban,Y,5849.0
1,Male,Yes,1.0,Graduate,No,128.000000,360.0,1.0,Rural,N,6091.0
2,Male,Yes,0.0,Graduate,Yes,66.000000,360.0,1.0,Urban,Y,3000.0
3,Male,Yes,0.0,Not Graduate,No,120.000000,360.0,1.0,Urban,Y,4941.0
4,Male,No,0.0,Graduate,No,141.000000,360.0,1.0,Urban,Y,6000.0

In [ ]:
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import MinMaxScaler, StandardScaler
from sklearn.preprocessing import LabelEncoder, MinMaxScaler
from xgboost import XGBClassifier
from sklearn.metrics import accuracy_score
from sklearn.model_selection import train_test_split

In [ ]:
# Convert categorical columns to binary
label_encoder = LabelEncoder()
categorical_cols = ['Gender', 'Married', 'Education', 'Self_Employed','Loan_Status']
for col in categorical_cols:
    df[col] = label_encoder.fit_transform(df[col])

In [ ]:
label_encoder = LabelEncoder()
categorical_cols = ['Property_Area']
for col in categorical_cols:
    df[col] = label_encoder.fit_transform(df[col])

In [ ]:

# Print the updated DataFrame
print(df)

     Gender  Married  Dependents  Education  Self_Employed  LoanAmount  \
0         1        0    0.000000          0              0  146.412162
1         1        1    1.000000          0              0  128.000000
2         1        1    0.000000          0              1   66.000000
3         1        1    0.000000          1              0  120.000000
4         1        0    0.000000          0              0  141.000000
..      ...      ...         ...        ...            ...         ...
609       0        0    0.000000          0              0   71.000000
610       1        1    0.554745          0              0   40.000000
611       1        1    1.000000          0              0  253.000000
612       1        1    2.000000          0              0  187.000000
613       0        0    0.000000          0              1  133.000000

     Loan_Amount_Term  Credit_History  Property_Area  Loan_Status  TotalIncome
0               360.0             1.0              2            1       5849.0
1               360.0             1.0              0            0       6091.0
2               360.0             1.0              2            1       3000.0
3               360.0             1.0              2            1       4941.0
4               360.0             1.0              2            1       6000.0
..                ...             ...            ...          ...          ...
609             360.0             1.0              0            1       2900.0
610             180.0             1.0              0            1       4106.0
611             360.0             1.0              2            1       8312.0
612             360.0             1.0              2            1       7583.0
613             360.0             0.0              1            0       4583.0

[614 rows x 11 columns]

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 614 entries, 0 to 613
Data columns (total 11 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Gender            614 non-null    int64
 1   Married           614 non-null    int64
 2   Dependents        614 non-null    float64
 3   Education         614 non-null    int64
 4   Self_Employed     614 non-null    int64
 5   LoanAmount        614 non-null    float64
 6   Loan_Amount_Term  614 non-null    float64
 7   Credit_History    614 non-null    float64
 8   Property_Area     614 non-null    int64
 9   Loan_Status       614 non-null    int64
 10  TotalIncome       614 non-null    float64
dtypes: float64(5), int64(6)
memory usage: 52.9 KB

In [ ]:
# Normalize the numerical columns using Min-Max Scaling
scaler = MinMaxScaler()
df[numerical_cols] = scaler.fit_transform(df[numerical_cols])

In [ ]:
# Print the updated DataFrame
print(df)

     Gender  Married  Dependents  Education  Self_Employed  LoanAmount  \
0         1        0    0.000000          0              0    0.198860
1         1        1    0.500000          0              0    0.172214
2         1        1    0.000000          0              1    0.082489
3         1        1    0.000000          1              0    0.160637
4         1        0    0.000000          0              0    0.191027
..      ...      ...         ...        ...            ...         ...
609       0        0    0.000000          0              0    0.089725
610       1        1    0.277372          0              0    0.044863
611       1        1    0.500000          0              0    0.353111
612       1        1    1.000000          0              0    0.257598
613       0        0    0.000000          0              1    0.179450

     Loan_Amount_Term  Credit_History  Property_Area  Loan_Status  TotalIncome
0            0.743590             1.0              2            1       5849.0
1            0.743590             1.0              0            0       6091.0
2            0.743590             1.0              2            1       3000.0
3            0.743590             1.0              2            1       4941.0
4            0.743590             1.0              2            1       6000.0
..                ...             ...            ...          ...          ...
609          0.743590             1.0              0            1       2900.0
610          0.358974             1.0              0            1       4106.0
611          0.743590             1.0              2            1       8312.0
612          0.743590             1.0              2            1       7583.0
613          0.743590             0.0              1            0       4583.0

[614 rows x 11 columns]

In [ ]:
df.head()

,Gender,Married,Dependents,Education,Self_Employed,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area,Loan_Status,TotalIncome
0,1,0,0.0,0,0,0.198860,0.74359,1.0,2,1,5849.0
1,1,1,0.5,0,0,0.172214,0.74359,1.0,0,0,6091.0
2,1,1,0.0,0,1,0.082489,0.74359,1.0,2,1,3000.0
3,1,1,0.0,1,0,0.160637,0.74359,1.0,2,1,4941.0
4,1,0,0.0,0,0,0.191027,0.74359,1.0,2,1,6000.0

In [ ]:
df['Property_Area'].value_counts()

Property_Area
1    233
2    202
0    179
Name: count, dtype: int64

In [ ]:
# Separate features (X) and target (y)
X = df.drop(columns=['Loan_Status'])
y = df['Loan_Status']

In [ ]:
# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [ ]:
# Apply XGBoost
model = XGBClassifier(use_label_encoder=False, eval_metric='logloss')
model.fit(X_train, y_train)

XGBClassifier(base_score=None, booster=None, callbacks=None,
              colsample_bylevel=None, colsample_bynode=None,
              colsample_bytree=None, device=None, early_stopping_rounds=None,
              enable_categorical=False, eval_metric='logloss',
              feature_types=None, gamma=None, grow_policy=None,
              importance_type=None, interaction_constraints=None,
              learning_rate=None, max_bin=None, max_cat_threshold=None,
              max_cat_to_onehot=None, max_delta_step=None, max_depth=None,
              max_leaves=None, min_child_weight=None, missing=nan,
              monotone_constraints=None, multi_strategy=None, n_estimators=None,
              n_jobs=None, num_parallel_tree=None, random_state=None, ...)

In [ ]:
y_pred = model.predict(X_test)

In [ ]:
# Evaluate the model
accuracy = accuracy_score(y_test, y_pred)
print(f'Accuracy: {accuracy}')

Accuracy: 0.7479674796747967